language: ruby
rvm:
  - 2.1.4
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/application.yml.sample config/application.yml
  - mv config/initializers/default_settings.rb tmp.rb
  - psql -c 'create database parasol;' -U postgres
  - bundle exec rake db:reset
  - mv tmp.rb config/initializers/default_settings.rb
script:
  - bundle exec rake spec
